# Arquivo de Tema com as cores da Goodyear
# .streamlit/config.toml

[theme]

# Cor primária (usada para botões, sliders, e outros elementos interativos)
primaryColor = "#FFD100" # Amarelo Goodyear

# Cor de fundo principal do aplicativo
backgroundColor = "#002856" # Azul Goodyear (um tom um pouco mais escuro para conforto visual)

# Cor de fundo secundária (usada na barra lateral e em outros elementos de fundo)
secondaryBackgroundColor = "#003DA5" # Azul Goodyear Principal

# Cor do texto
textColor = "#FFFFFF" # Branco, para bom contraste com o fundo azul

# Fonte padrão
font = "sans serif"
